export const templates = [
  {
    id: 1,
    name: 'Business Dashboard',
    description: 'This is a short description of Template 1.',
    image: '/img/cat1.jpg',
    author: 'Sir Whiskers McFluffington',
    demoLink: 'https://example.com',
    framework: 'Next.js',
    css: 'Tailwind',
    database: 'PostgreSQL',
    cms: 'Strapi',
    authentication: 'JWT',
    analytics: 'Google Analytics',
    useCase: 'SaaS'
  },
  {
    id: 2,
    name: 'Portfolio Template',
    description: 'This is a short description of Template 2.',
    image: '/img/cat2.jpg',
    author: 'Princess Purrington',
    demoLink: 'https://example.com',
    framework: 'React',
    css: 'Bootstrap',
    database: 'MongoDB',
    cms: 'WordPress',
    authentication: 'Magic Links',
    analytics: 'Plausible',
    useCase: 'Portfolio'
  },
  {
    id: 3,
    name: 'Blog Template',
    description: 'This is a short description of Template 3.',
    image: '/img/cat3.jpg',
    author: 'Lord Fluffernutter',
    demoLink: 'https://example.com',
    framework: 'Vue',
    css: 'CSS Modules',
    database: 'Firebase',
    cms: 'Sanity',
    authentication: 'OAuth',
    analytics: 'Posthog',
    useCase: 'Blog'
  },
  {
    id: 4,
    name: 'E-Commerce Template',
    description: 'This is a short description of Template 4.',
    image: '/img/cat4.jpg',
    author: 'Captain Meowington',
    demoLink: 'https://example.com',
    framework: 'Next.js',
    css: 'Tailwind',
    database: 'PostgreSQL',
    cms: 'Strapi',
    authentication: 'JWT',
    analytics: 'Google Analytics',
    useCase: 'E-Commerce'
  },
  {
    id: 5,
    name: 'Landing Page Template',
    description: 'This is a short description of Template 5.',
    image: '/img/cat5.jpg',
    author: 'Countess Mewina von Purr',
    demoLink: 'https://example.com',
    framework: 'React',
    css: 'Bootstrap',
    database: 'MongoDB',
    cms: 'WordPress',
    authentication: 'Magic Links',
    analytics: 'Plausible',
    useCase: 'Landing Page'
  },
  {
    id: 6,
    name: 'Admin Dashboard',
    description: 'This is a short description of Template 6.',
    image: '/img/cat6.jpg',
    author: 'Baroness Furrington',
    demoLink: 'https://example.com',
    framework: 'Vue',
    css: 'CSS Modules',
    database: 'Firebase',
    cms: 'Sanity',
    authentication: 'OAuth',
    analytics: 'Posthog',
    useCase: 'Admin Dashboard'
  },
  {
    id: 7,
    name: 'Social Media Template',
    description: 'This is a short description of Template 7.',
    image: '/img/cat7.jpg',
    author: 'Meowster von Snugglepaws',
    demoLink: 'https://example.com',
    framework: 'Next.js',
    css: 'Tailwind',
    database: 'PostgreSQL',
    cms: 'Strapi',
    authentication: 'JWT',
    analytics: 'Google Analytics',
    useCase: 'Social Media'
  },
  {
    id: 8,
    name: 'News Website Template',
    description: 'This is a short description of Template 8.',
    image: '/img/cat8.jpg',
    author: 'Lady Purrfect',
    demoLink: 'https://example.com',
    framework: 'React',
    css: 'Bootstrap',
    database: 'MongoDB',
    cms: 'WordPress',
    authentication: 'Magic Links',
    analytics: 'Plausible',
    useCase: 'News Website'
  },
  {
    id: 9,
    name: 'Corporate Website Template',
    description: 'This is a short description of Template 9.',
    image: '/img/cat9.jpg',
    author: 'Sir Meowington III',
    demoLink: 'https://example.com',
    framework: 'Vue',
    css: 'CSS Modules',
    database: 'Firebase',
    cms: 'Sanity',
    authentication: 'OAuth',
    analytics: 'Posthog',
    useCase: 'Corporate Website'
  },
  {
    id: 10,
    name: 'Event Template',
    description: 'This is a short description of Template 10.',
    image: '/img/cat10.jpg',
    author: 'Baron von Purrsley',
    demoLink: 'https://example.com',
    framework: 'Next.js',
    css: 'Tailwind',
    database: 'PostgreSQL',
    cms: 'Strapi',
    authentication: 'JWT',
    analytics: 'Google Analytics',
    useCase: 'Event'
  }
];
